In [ ]:
### JALANKAN CELL INI TERLEBIH DAHULU ###
!pip install sqlalchemy==1.4.46
!pip install pandasql

Collecting sqlalchemy==1.4.46
  Downloading SQLAlchemy-1.4.46-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 8.3 MB/s eta 0:00:00
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy==1.4.46) (3.0.3)
Installing collected packages: sqlalchemy
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 2.0.29
    Uninstalling SQLAlchemy-2.0.29:
      Successfully uninstalled SQLAlchemy-2.0.29
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython-sql 0.5.0 requires sqlalchemy>=2.0, but you have sqlalchemy 1.4.46 which is incompatible.
Successfully installed sqlalchemy-1.4.46
Collecting pandasql
  Downloading pandasql-0.7.3.tar.gz (26 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from pandasql) (1.25.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from pandasql) (2.0.3)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.10/dist-packages (from pandasql) (1.4.46)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->pandasql) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->pandasql) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas->pandasql) (2024.1)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy->pandasql) (3.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->pandasql) (1.16.0)
Building wheels for collected packages: pandasql
  Building wheel for pandasql (setup.py) ... done
  Created wheel for pandasql: filename=pandasql-0.7.3-py3-none-any.whl size=26771 sha256=3faedb17395a66b26c6de2531510b4fbee1c5089bf9ecd748e60a18031b3e4ac
  Stored in directory: /root/.cache/pip/wheels/e9/bc/3a/8434bdcccf5779e72894a9b24fecbdcaf97940607eaf4bcdf9
Successfully built pandasql
Installing collected packages: pandasql
Successfully installed pandasql-0.7.3

In [ ]:
import pandas as pd
import pandasql

from pandasql import sqldf
sql_run = lambda q: sqldf(q, globals())

In [ ]:
worldcity = pd.read_csv('worldcities.csv', sep = ';', encoding = 'latin-1')
uscity = pd.read_csv('uscities.csv', sep = ';', encoding = 'latin-1')
uscity.columns = ['city', 'state_id', 'state_name', 'county_fips', 'county_name',
       'lat', 'lng', 'population', 'density', 'source', 'military',
       'incorporated', 'timezone', 'ranking', 'zips', 'id']

### Tutorial Bagaimana Cara Melakukan Query Menggunakan Pandasql

Contoh: Bagaimana melakukan query untuk mendapatkan kota-kota dari worldcity yang merupakan:
- berada di antara 33 - 40 'latitude'
- berada di antara 100 - 140 'longitude'
- merupakan kota 'primary' pada kolom 'capital'
- memiliki populasi lebih dari 20 juta

In [ ]:
worldcity

,city,lat,lng,country,iso2,iso3,capital,population,id
0,Tokyo,35.6897,139.6922,Japan,JP,JPN,primary,37977000.0,1392685764
1,Jakarta,-6.2146,106.8451,Indonesia,ID,IDN,primary,34540000.0,1360771077
2,Delhi,28.6600,77.2300,India,IN,IND,admin,29617000.0,1356872604
3,Mumbai,18.9667,72.8333,India,IN,IND,admin,23355000.0,1356226629
4,Manila,14.6000,120.9833,Philippines,PH,PHL,primary,23088000.0,1608618140
...,...,...,...,...,...,...,...,...,...
40996,Tukchi,57.3670,139.5000,Russia,RU,RUS,NaN,10.0,1643472801
40997,Numto,63.6667,71.3333,Russia,RU,RUS,NaN,10.0,1643985006
40998,Nord,81.7166,-17.8000,Greenland,GL,GRL,NaN,10.0,1304217709
40999,Timmiarmiut,62.5333,-42.2167,Greenland,GL,GRL,NaN,10.0,1304206491
41000,Nordvik,74.0165,111.5100,Russia,RU,RUS,NaN,0.0,1643587468

In [ ]:
uscity

,city,state_id,state_name,county_fips,county_name,lat,lng,population,density,source,military,incorporated,timezone,ranking,zips,id
0,New York,NY,New York,36061,New York,40.6943,-73.9249,18713220,10715,polygon,False,True,America/New_York,1,11229 11226 11225 11224 11222 11221 11220 1138...,1840034016
1,Los Angeles,CA,California,6037,Los Angeles,34.1139,-118.4068,12750807,3276,polygon,False,True,America/Los_Angeles,1,90291 90293 90292 91316 91311 90037 90031 9000...,1840020491
2,Chicago,IL,Illinois,17031,Cook,41.8373,-87.6862,8604203,4574,polygon,False,True,America/Chicago,1,60018 60649 60641 60640 60643 60642 60645 6064...,1840000494
3,Miami,FL,Florida,12086,Miami-Dade,25.7839,-80.2102,6445545,5019,polygon,False,True,America/New_York,1,33129 33125 33126 33127 33128 33149 33144 3314...,1840015149
4,Dallas,TX,Texas,48113,Dallas,32.7936,-96.7662,5743938,1526,polygon,False,True,America/Chicago,1,75287 75098 75233 75254 75251 75252 75253 7503...,1840019440
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28333,Gross,NE,Nebraska,31015,Boyd,42.9461,-98.5697,2,6,polygon,False,True,America/Chicago,3,68719,1840011032
28334,Lotsee,OK,Oklahoma,40143,Tulsa,36.1334,-96.2091,2,39,polygon,False,True,America/Chicago,3,74063,1840021674
28335,The Ranch,MN,Minnesota,27087,Mahnomen,47.3198,-95.6952,2,2,polygon,False,True,America/Chicago,3,56557,1840039629
28336,Shamrock,OK,Oklahoma,40037,Creek,35.9113,-96.5772,2,2,polygon,False,True,America/Chicago,3,74068,1840022701
28337,Monowi,NE,Nebraska,31015,Boyd,42.8307,-98.3296,1,1,polygon,False,True,America/Chicago,3,68746,1840011034

In [ ]:
query = """
SELECT DISTINCT city
FROM worldcity
WHERE lat BETWEEN 33 and 40
AND lng BETWEEN 100 and 140
AND capital = 'primary'
AND population > 20000000
"""

sql_run(query)

    city
0  Tokyo
1  Seoul

In [ ]:
query = """
SELECT DISTINCT city
FROM worldcity
"""


sql_run(query)

              city
0            Tokyo
1          Jakarta
2            Delhi
3           Mumbai
4           Manila
...            ...
37494       Tukchi
37495        Numto
37496         Nord
37497  Timmiarmiut
37498      Nordvik

[37499 rows x 1 columns]

### Question 1 Point : 40

Temukan kota-kota dari worldcity yang memenuhi semua kondisi ini:
- populasi kota tersebut melebih populasi dari kota terbanyak penduduknya di negara Filipina. (Maksudnya: misalnya kota X adalah kota di Filipina yang paling banyak penduduknya. Kita mau daftar kota-kota yang jumlah penduduknya lebih besar dari kota X tersebut), DAN
- ada kota di Amerika Serikat (uscity) dengan nama kota yang sama dengan kota-kota pilihan

Keluarkan hanya nama kota-kota yang memenuhi 2 syarat di atas saja, tidak usah kolom-kolom lain.

##### NOTE: Hilangkan duplicate rows.

Lakukan hanya 1x query saja, jangan melakukan lebih dari 1 query

In [ ]:
query = """
SELECT DISTINCT w.city
FROM worldcity AS w
WHERE
    population >
    (SELECT
        MAX(population)
    FROM worldcity
    WHERE
        country = 'Philippines') AND
    EXISTS (SELECT *
    FROM uscity AS u
    WHERE u.city = w.city)

"""


sql_run(query)

    city
0  Delhi

### Question 2 Point : 60

Temukan kota-kota di Amerika Serikat (uscity) yang memenuhi semua kondisi berikut:
- memiliki nama 'city' yang tidak sama dengan 'state_name', dan juga
- memiliki populasi di atas rata-rata populasi kota-kota di 'county_name' Miami-Dade, dan juga
- terdiri dari dua atau lebih kata (contoh: Los Angeles, New York)

Output yang diharapkan hanya kolom 'city' saja, tidak usah kolom yang lain

Lakukan hanya 1x query saja, jangan melakukan lebih dari 1 query

In [ ]:
query = """
SELECT DISTINCT city
FROM uscity
WHERE
  population > (SELECT AVG(population)
  FROM uscity
  WHERE county_name = 'Miami-Dade')
  AND city != state_name AND city LIKE '% %' """

sql_run(query)

                city
0        Los Angeles
1      San Francisco
2          San Diego
3          Las Vegas
4        San Antonio
..               ...
84        South Lyon
85      Lehigh Acres
86  East Los Angeles
87        St. George
88         Yuba City

[89 rows x 1 columns]